In [ ]:
# Import PyTorch and print the version
import torch
print(torch.__version__)

2.11.0+cpu


In [ ]:
# Check for GPU availability in PyTorch
if torch.cuda.is_available():
    print("Available GPU:", torch.cuda.get_device_name(0))
else:
    print("No GPU detected. Running on CPU.")


Missing GPU


### *Creating Tensors*

### *==Scalar operation==*

In [ ]:
# Create an uninitialized (empty) tensor of shape 3x4
x = torch.empty(3, 4)

In [ ]:
# Display the tensor and its type
x, type(x)

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.Tensor)

In [ ]:
# Create a tensor filled with zeros of shape 2x3
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# Create a tensor filled with ones of shape 2x3
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# Create a tensor with random values of shape 2x3
torch.rand(2, 3)

tensor([[0.3238, 0.4651, 0.8021],
        [0.1931, 0.7786, 0.8010]])

In [ ]:
# Set the seed for reproducibility of random numbers
# After setting the seed, the following rand calls will produce the same values every time

torch.manual_seed(100)
torch.rand(2, 3), torch.rand(2, 3), torch.rand(2, 3)

(tensor([[0.1117, 0.8158, 0.2626],
         [0.4839, 0.6765, 0.7539]]),
 tensor([[0.2627, 0.0428, 0.2080],
         [0.1180, 0.1217, 0.7356]]),
 tensor([[0.7118, 0.7876, 0.4183],
         [0.9014, 0.9969, 0.7565]]))

In [ ]:
# Generate another random tensor (seed not set here, so values may differ)
torch.rand(2, 3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
# Create a tensor from a Python list
torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# Create a 1D tensor with values from 1 to 9 (step size 2)
torch.arange(1, 10, 2)

tensor([1, 3, 5, 7, 9])

In [ ]:
# Create a 1D tensor with 9 values evenly spaced between 2 and 8
torch.linspace(2, 8, 9)

tensor([2.0000, 2.7500, 3.5000, 4.2500, 5.0000, 5.7500, 6.5000, 7.2500, 8.0000])

In [41]:
torch.eye(2,4), torch.eye(6)

(tensor([[1., 0., 0., 0.],
         [0., 1., 0., 0.]]),
 tensor([[1., 0., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0., 0.],
         [0., 0., 1., 0., 0., 0.],
         [0., 0., 0., 1., 0., 0.],
         [0., 0., 0., 0., 1., 0.],
         [0., 0., 0., 0., 0., 1.]]))

In [43]:
torch.full((4,5), 7)

tensor([[7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7]])

### *Tensor Shapes*

In [52]:
t = torch.tensor([[1,2,3],[4,5,6]])
t, t.shape

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 torch.Size([2, 3]))

In [54]:
torch.empty_like(t), torch.zeros_like(t), torch.ones_like(t)

(tensor([[4592710681114968064, 4605523680955465728, 4598401516003393536],
         [4602388383820414976, 4604268622255226880, 4604965845771223040]]),
 tensor([[0, 0, 0],
         [0, 0, 0]]),
 tensor([[1, 1, 1],
         [1, 1, 1]]))

In [60]:
# as t is int so it will throw error so need to change to float32
torch.rand_like(t, dtype=torch.float32)

tensor([[0.5277, 0.2472, 0.7909],
        [0.4235, 0.0169, 0.2209]])

### *Tensor Data Types*

In [ ]:
# Create a tensor of ones with int16 data type
a = torch.ones((2, 3), dtype=torch.int16)
a

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)

In [74]:
# So, 20 is just a multiplier that changes the range of the random values from 0, 1) to 0, 4.)
# multiplying by 20 or 20. will both work, but using 20. makes it explicit that you are working with floating-point numbers,
# which matches the dtype=torch.float64 of your tensor. 
# This helps avoid type mismatch issues and is good practice when working with floating-point tensors.
multby = 4. # tells its float , if 4 means int
b = torch.rand((2, 3), dtype=torch.float64) * multby
b

tensor([[0.1344, 1.2060, 2.2508],
        [3.6270, 0.6403, 2.0285]], dtype=torch.float64)

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


### *==Mathematical operations==*

In [ ]:
# Create a tensor of ones by adding 1 to a zeros tensor
ones = torch.zeros(2, 2) + 1
ones

tensor([[1., 1.],
        [1., 1.]])

In [ ]:
# Multiply a tensor of ones by 2 to get a tensor of twos
twos = torch.ones(2, 2) * 2
twos

tensor([[2., 2.],
        [2., 2.]])

In [ ]:
# Arithmetic operations on tensors
# Multiply by 7, subtract 1, then divide by 2
result1 = torch.ones(2, 2) * 7 - 1
result2 = result1 / 2
result1, result2

(tensor([[6., 6.],
         [6., 6.]]),
 tensor([[3., 3.],
         [3., 3.]]))

In [90]:
fours = twos ** 2
sqrt2s = twos ** 0.5
fours, sqrt2s

(tensor([[4., 4.],
         [4., 4.]]),
 tensor([[1.4142, 1.4142],
         [1.4142, 1.4142]]))

In [ ]:
# Element-wise addition and subtraction of tensors
a = torch.rand(2, 3)
b = torch.rand(2, 3)
sum_ab = a + b
diff_ab = a - b
a, b, sum_ab, diff_ab

(tensor([[0.3436, 0.2028, 0.9792],
         [0.4947, 0.3617, 0.9687]]),
 tensor([[0.0359, 0.3041, 0.9867],
         [0.1290, 0.6887, 0.1637]]),
 tensor([[0.3795, 0.5069, 1.9659],
         [0.6237, 1.0504, 1.1323]]),
 tensor([[ 0.3077, -0.1013, -0.0075],
         [ 0.3657, -0.3270,  0.8050]]))

In [92]:
s = torch.tensor([1, -2, 3, -4])
s, torch.abs(s), torch.neg(s)

(tensor([ 1, -2,  3, -4]), tensor([1, 2, 3, 4]), tensor([-1,  2, -3,  4]))

In [ ]:
# Rounding operations on tensors
m = torch.tensor([1.9, 2.3, 3.7, 4.4])
ceil_m = torch.ceil(m)
round_m = torch.round(m)
floor_m = torch.floor(m)
m, ceil_m, round_m, floor_m

(tensor([1.9000, 2.3000, 3.7000, 4.4000]),
 tensor([2., 3., 4., 5.]),
 tensor([2., 2., 4., 4.]),
 tensor([1., 2., 3., 4.]))

In [ ]:
# Clamp tensor values to a specified range
# All values below 2 become 2, all above 3 become 3
clamped = torch.clamp(m, min=2, max=3)
clamped

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### *==Element wise operation==*

In [ ]:
# Create a random integer tensor and compute sum, mean, and median
z = torch.randint(size=(2, 3), low=0, high=10, dtype=torch.float32)
sum_z = torch.sum(z)
mean_z = torch.mean(z)
median_z = torch.median(z)
z, sum_z, mean_z, median_z

(tensor([[1., 4., 2.],
         [6., 5., 8.]]),
 tensor(26.),
 tensor(4.3333),
 tensor(4.))

In [ ]:
# Mean along different dimensions
mean_all = torch.mean(z)
mean_dim0 = torch.mean(z, dim=0)
mean_dim1 = torch.mean(z, dim=1)
mean_all, mean_dim0, mean_dim1

(tensor(4.3333), tensor([3.5000, 4.5000, 5.0000]), tensor([2.3333, 6.3333]))

In [111]:
torch.max(z), torch.min(z)

(tensor(8.), tensor(1.))

In [ ]:
# If z = torch.tensor([2, 3, 4]), then torch.prod(z) returns 24 (because 2 × 3 × 4 = 24).
prod_z = torch.prod(z)
prod_z

tensor(1920.)

### *Formula For std*
$$\text{std}(x) = \sqrt{\frac{1}{n-1} \sum_{i=1}^n (x_i - \mu)^2}$$

In [114]:
#The standard deviation (std) in PyTorch is calculated as the square root of the average of the squared differences from the mean
torch.std(z)

tensor(2.5820)

  ### *Formula for Variance*

$$
\text{var}(x) = \frac{1}{n-1} \sum_{i=1}^n (x_i - \mu)^2
$$

Where:
- $x_i$ are the elements of the tensor
- $\mu$ is the mean of the tensor
- $n$ is the number of elements

In [116]:
# - Variance measures how far the values in the tensor are spread out from the mean.
torch.var(z)

tensor(6.6667)

In [118]:
#Returns the indices of the maximum value of all elements in the :attr:`input` tensor.
torch.argmax(z), torch.argmin(z),

(tensor(5), tensor(0))

### *==Matrix operations==*

In [119]:
m1 = torch.randint(size=(2,3), low=0, high=10)
m2 = torch.randint(size=(3,2), low=0, high=10)

m1, m2

(tensor([[7, 0, 3],
         [9, 2, 2]]),
 tensor([[0, 3],
         [6, 4],
         [6, 6]]))

In [120]:
torch.matmul(m1,m2)

tensor([[18, 39],
        [24, 47]])

In [ ]:
# If a = torch.tensor([a1, a2, a3]) and b = torch.tensor([b1, b2, b3]), then torch.dot(a, b) returns a1b1 + a2b2 + a3*b3.
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

torch.dot(vector1, vector2)

tensor(11)

In [ ]:
# torch.transpose swaps two dimensions of a tensor. For 2D tensors, it is equivalent to matrix transpose.
# Syntax: torch.transpose(input, dim0, dim1)
# Example: For a 2x3 tensor, swapping dim0 and dim1 gives a 3x2 tensor.
# Let's create a tensor and transpose it:
f = torch.tensor([[1, 2, 3], [4, 5, 6]])
print('Original tensor:')
print(f)
print('Transposed tensor:')
print(torch.transpose(f, 0, 1))

### *==Reduction operation==*

In [123]:
intmat = torch.randint(size=(3,3), low=0, high=10)
int_float_mat = intmat.to(torch.float32)

intmat, int_float_mat

(tensor([[5, 8, 2],
         [5, 5, 2],
         [9, 5, 9]]),
 tensor([[5., 8., 2.],
         [5., 5., 2.],
         [9., 5., 9.]]))

### torch.det: Determinant of a Matrix
- For a 2x2 matrix $A = \begin{bmatrix} a & b \\ c & d \end{bmatrix}$, $\text{det}(A) = ad - bc$.
```python
matrix = torch.tensor([[1., 2.], [3., 4.]])
det = torch.det(matrix)  # Returns -2.0
```

In [126]:
torch.det(int_float_mat)

tensor(-81.)

#### How torch.inverse Calculates the Inverse
- For a 2x2 matrix $A = \begin{bmatrix} a & b \\ c & d \end{bmatrix}$, the inverse is:
$$
A^{-1} = \frac{1}{ad-bc} \begin{bmatrix} d & -b \\ -c & a \end{bmatrix}
$$

In [127]:
torch.inverse(int_float_mat)

tensor([[-4.3210e-01,  7.6543e-01, -7.4074e-02],
        [ 3.3333e-01, -3.3333e-01, -1.0568e-10],
        [ 2.4691e-01, -5.8025e-01,  1.8519e-01]])

### == *Comparison operations*  ==

In [143]:
c1>c2, c1<c2, c1==c2, c1!=c2

(tensor([[False, False,  True],
         [False,  True,  True]]),
 tensor([[ True,  True, False],
         [ True, False, False]]),
 tensor([[False, False, False],
         [False, False, False]]),
 tensor([[True, True, True],
         [True, True, True]]))

### *==Special Function ==*

## TODO

In [146]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[4., 8., 8.],
        [1., 2., 4.]])

In [ ]:

torch.log(k)

tensor([[1.3863, 2.0794, 2.0794],
        [0.0000, 0.6931, 1.3863]])

In [148]:
torch.exp(k)

tensor([[5.4598e+01, 2.9810e+03, 2.9810e+03],
        [2.7183e+00, 7.3891e+00, 5.4598e+01]])

In [149]:
torch.sigmoid(k)

tensor([[0.9820, 0.9997, 0.9997],
        [0.7311, 0.8808, 0.9820]])

In [150]:
torch.softmax(k, dim=0)

tensor([[0.9526, 0.9975, 0.9820],
        [0.0474, 0.0025, 0.0180]])

### ==*Inplace Operations*==
# TODO

In [152]:
m = torch.rand(2,3)
n = torch.rand(2,3)

m,n

(tensor([[0.8060, 0.7267, 0.8054],
         [0.1696, 0.2023, 0.9194]]),
 tensor([[0.0151, 0.0324, 0.9538],
         [0.5564, 0.7567, 0.1573]]))

In [154]:
m.add_(n)
m, n

(tensor([[0.8362, 0.7915, 2.7131],
         [1.2825, 1.7158, 1.2340]]),
 tensor([[0.0151, 0.0324, 0.9538],
         [0.5564, 0.7567, 0.1573]]))

In [155]:
torch.relu(m), m.relu_()

(tensor([[0.8362, 0.7915, 2.7131],
         [1.2825, 1.7158, 1.2340]]),
 tensor([[0.8362, 0.7915, 2.7131],
         [1.2825, 1.7158, 1.2340]]))

### ==*Copying a Tensor*==

In [157]:
a = torch.rand(2,3)
a

tensor([[0.3969, 0.2381, 0.1268],
        [0.4460, 0.0370, 0.6442]])

In [158]:
b=a
b

tensor([[0.3969, 0.2381, 0.1268],
        [0.4460, 0.0370, 0.6442]])

In [161]:
a[0][0]=0
a

tensor([[0.0000, 0.2381, 0.1268],
        [0.4460, 0.0370, 0.6442]])

In [162]:
b

tensor([[0.0000, 0.2381, 0.1268],
        [0.4460, 0.0370, 0.6442]])

In [163]:
id(a), id(b)

(2635888183488, 2635888183488)

In [164]:
b = a.clone()
a,b

(tensor([[0.0000, 0.2381, 0.1268],
         [0.4460, 0.0370, 0.6442]]),
 tensor([[0.0000, 0.2381, 0.1268],
         [0.4460, 0.0370, 0.6442]]))

In [165]:
a[0][0] = 10
a,b

(tensor([[10.0000,  0.2381,  0.1268],
         [ 0.4460,  0.0370,  0.6442]]),
 tensor([[0.0000, 0.2381, 0.1268],
         [0.4460, 0.0370, 0.6442]]))

In [166]:
id(a), id(b)

(2635888183488, 2635900877424)